# Generated by Django 2.0 on 2018-03-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20180327_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='date published'),
        ),
    ]
