# Generated by Django 2.0 on 2018-03-27 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20180327_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='date published'),
        ),
    ]
